<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TalkFolio\TalkFolio.csproj" />
    <ProjectReference Include="..\TalkFolio.Data.YamlFile\TalkFolio.Data.YamlFile.csproj" />
  </ItemGroup>

</Project>